# Generated by Django 3.1.4 on 2020-12-11 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contentblocklist',
            name='content',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.contentblock'),
        ),
        migrations.AddField(
            model_name='contentblocklist',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_fk', to='api.task'),
        ),
        migrations.AddField(
            model_name='comment',
            name='content_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_fk', to='api.contentblocklist'),
        ),
    ]
